service: simple-lambda
frameworkVersion: "3"

plugins:
  - serverless-esbuild

package:
  individually: true

params:
  default:
    INFRA_NAME: 'lambda-infra-${opt:stage}'

custom:
  esbuild:
    bundle: true
    minify: false
    watch:
      pattern: ["src"]
    target: node18

provider:
  name: aws
  runtime: nodejs18.x
  logRetentionInDays: 90
  versionFunctions: false
  timeout: 30
  environment:
    stage: ${opt:stage}
    BUCKET_NAME:
      Fn::ImportValue: ${param:INFRA_NAME}-SimpleBucketName


functions:
  example:
    name: simple-${opt:stage}
    role:
      Fn::ImportValue: ${param:INFRA_NAME}-SimpleBucketRoleArn
    handler: ./src/handler.simple
